services:
  - type: web
    name: django-realestate
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn realestate.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: realestate.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
